# Generated by Django 3.2.5 on 2021-12-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0002_auto_20211221_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='food',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='price',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
