# Generated by Django 3.2.5 on 2021-12-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0003_auto_20211221_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC_facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout', models.CharField(choices=[('Indoors', 'in'), ('Outdoors', 'out')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmas.address')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmas.price')),
            ],
        ),
        migrations.CreateModel(
            name='BookStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmas.address')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmas.price')),
            ],
        ),
    ]
