# Generated by Django 3.2.5 on 2021-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0005_dc_facts_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstores',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
