# Generated by Django 3.2.5 on 2022-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0007_entertainment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='timeOfday',
            field=models.CharField(choices=[('Day', 'Daytime'), ('Night', 'Nightime')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='inout',
            field=models.CharField(choices=[('Indoors', 'Indoors'), ('Outdoors', 'Outdoors')], max_length=20),
        ),
    ]
