# Generated by Django 3.2.5 on 2022-01-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0008_auto_20220110_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='timeOfday',
            field=models.CharField(choices=[('Day', 'Daytime'), ('Night', 'Nightime'), ('both', 'Both')], max_length=20),
        ),
    ]
