# Generated by Django 3.2.5 on 2022-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0009_alter_entertainment_timeofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='link',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='link',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
