# Generated by Django 3.2.5 on 2022-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0010_auto_20220112_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
