# Generated by Django 3.2.5 on 2022-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0011_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstores',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstores',
            name='link',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
