# Generated by Django 3.2.5 on 2022-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0012_auto_20220112_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodtype',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
