# Generated by Django 3.2.5 on 2022-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0013_auto_20220112_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
        migrations.AlterField(
            model_name='food',
            name='foodtype',
            field=models.CharField(max_length=200),
        ),
    ]
