# Generated by Django 3.2.5 on 2022-01-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0014_auto_20220112_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='foodtype',
        ),
    ]
