# Generated by Django 3.2.5 on 2022-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0015_remove_food_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodtype',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
