# Generated by Django 3.2.5 on 2022-01-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmas', '0016_food_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodtype',
            field=models.CharField(max_length=50),
        ),
    ]
